# Generated by Django 6.0.4 on 2026-06-17 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('penerbit', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('rak', models.CharField(blank=True, max_length=50, null=True)),
                ('stok', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('keperluan', models.TextField(blank=True, null=True)),
                ('petugas', models.CharField(default='Budi Siregar', max_length=100)),
                ('sudah_kembali', models.BooleanField(default=False)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.siswa')),
            ],
        ),
    ]
